### ISSUE TITLE
Esquema de encriptacion inseguro

### ISSUE THREAD

**Issue by luismasuelli** [Kushki/kushki-php#1]
Por favor notar que estan usando un esquema de encriptacion que, si bien esta basado en RSA, es susceptible a un ataque de textos conocidos (estan usando actualmente OPENSSL_PKCS1_PADDING). Estimo que, como los esquemas entre el cliente y el servidor deben ser iguales, o bien no va a andar o bien en las librerias y en el servidor puede haber una vulnerabilidad que se puede tornar critica en un sistema de pagos. Por el bien de la plataforma arreglenlo, y si pueden usar algun esquema de PKCS que sea compatible con PyCrypto, mejor (estoy haciendo el adaptador de kushki para Python pero no me atrevo a continuar hasta que este punto se encuentre arreglado). Enlace con el issue de PHP: http://php.net/manual/es/function.openssl-public-encrypt.php (buscar comentario que comienza con: "We can't guarantee that RSA", sin comillas por supuesto).

**Comment by mayait** [comment]
¿Está arreglado?

**Comment by mayait** [comment]
Hola @luismasuelli, ¿Finalmente funciona tu adaptador de Python?
https://github.com/luismasuelli/kushki-python

Me dejaste preocupado con este comentario. ¿Conoces alguna opción ademas de kushki en Ecuador?

**Comment by joseSantacruz** [comment]
Cierro el issue porque ya no se ocupa este protocolo y ya la nueva version tiene otras arquitectura

**Comment by joseSantacruz** [comment]
@mayait para python puedes consumir directamente nuestro [API](https;//api.kushkipagos.com)
